### PR TITLE
Enable to stop one or more playgrounds

### PR DESCRIPTION
**Pull request by jedrekdomanski**

### CODE REVIEW

**Comment by iximiuz** [comment]
Nice catch!

**Comment by jedrekdomanski** [comment]
I didn' push all changes yet 😀 I opened the PR prematurely. My bad.
What I was trying to achieve is the docker like command:

docker stop cont1 cont2 cont3

labctl playground stop play1 play2 play3

I'll make a new PR.

**Comment by iximiuz** [comment]
Oops, thought you were correcting the help output. Looking forward to the next PR then!

**Comment by jedrekdomanski** [comment]
That's totally on me. Sorry for the confusion, Ivan🤦‍♂️ I should've pushed all the changes all together. I'm just used to my daily work workflow 🙂

**Comment by iximiuz** [comment]
Haha, no worries! I can definitely relate.

**Pull request merged**
